basePath: /demo-gin-api
host: 127.0.0.1:8080
info:
  contact:
    email: qoo753951ooq@gmail.com
    name: Alan Syu
  description: Demo Swagger 說明文件
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Demo API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
